# mutex package to keep only one MSYS2 env in a given conda env
# using the MSYS2 package epoch: Jul 28 2026 14:00:00 UTC
package:
  name: msys2-msys-mutex
  version: 1.0

build:
  number: 0
  string: gfw

about:
  summary: A mutex package to ensure environment exclusivity between MSYS2 MSYS environments
